config/routes.rb
Acmqdb::Application.routes.draw do
  resources :votes, :only => [:create, :show]

  resources :quotes, :only => [:create, :show, :index]

  match '/vote/:quote/:direction' => 'votes#create', :as => 'shortvote', :quote => /\d+/, :direction => /(?:up|down)/

  match '/top/' => 'quotes#top_rated'

  root :to => 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :votes
  cattr_reader :per_page
  @@per_page = 10
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :quote
  #validates_uniqueness_of :ip_address, :scope => :quote_id, :message => "has already rated this quote."
  validates_presence_of :quote_id, :ip_address, :direction
  validates_associated :quote

  named_scope :up, :conditions => {:direction => '+'}
  named_scope :down, :conditions => {:direction => '-'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # before_filter :connect_irc, :only => [:create]

  # GET /quotes
  # GET /quotes.xml
  def index
    @quote = Quote.new
    # @quotes = Quote.paginate :page => params[:page], :include => :votes, :order => 'created_at DESC'
    @quotes = Quote.order('created_at DESC').page(params[:page]).per(10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.xml
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.xml
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.xml
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to(@quote, :notice => 'Quote was successfully created.') }
        format.xml  { render :xml => @quote, :status => :created, :location => @quote }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.xml
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to(@quote, :notice => 'Quote was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.xml
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to(quotes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes/1
  # GET /votes/1.xml
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  # POST /votes
  def create
    @vote = Vote.new(params[:vote])

    case params[:direction]
    when 'up'
      @vote.direction = '+'
    when 'down'
      @vote.direction = '-'
    end

    @vote.ip_address = request.env['REMOTE_ADDR']
    @vote.quote_id ||= params[:quote].to_i

    # Delete any previous vote on the same quote, from the same IP
    Vote.destroy_all({:ip_address => @vote.ip_address, :quote_id => @vote.quote_id})

    respond_to do |format|
      if @vote.save
        format.html { redirect_to(vote_path(@vote, :page => params[:page]), :notice => 'Vote was successfully created.') }
      else
        format.html { redirect_to(@vote.quote, :notice => 'There was an error processing your vote. Please try again.') }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neptune QDB</title>
  <%= stylesheet_link_tag 'neptune' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <h1><%= link_to 'Neptune QDB', root_path %></h1>
  </div>
  <div id="content">
    <%= yield %>
  </div>
  <div id="footer">
    Total quotes: <%= Quote.count %> <br /> &copy; 2011 Ricky Elrod
  </div>
</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_area :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<div id="quotewall">
  <!--  <div class="quote">
        <div class="header">
          <div class="alleft">
          </div>
          <div class="alright">
          </div>
        </div>
        <div class="main">
        </div>
  </div>-->

<script>
  $(document).ready(function(){
    $(".foobar").hide();
    $("a.haithar").click(function ( event ) {
      event.preventDefault();
      $(this).hide();
      $(".foobar").show();
    });
  });
</script>

<!--<a href='#' class='haithar'>New Quote (will eventually place a quote box here)</a>
<div class="foobar" style="background-color: red; height: 20px; width: 20px;">hi</div>-->
  <% @quotes.each do |quote| %>

    <div class="quote">
      <div class="header">
        <div class="alleft">
          <%= link_to image_tag('upboat.png'), shortvote_path({:direction => 'up', :quote => quote.id, :page => params[:page]}) %>
          <%= quote.votes.up.count %>
          <%= link_to image_tag('downboat.png'), shortvote_path({:direction => 'down', :quote => quote.id, :page => params[:page]}) %>
          <%= quote.votes.down.count %>
        </div>
        <div class="alright">
          Total Votes: <%= quote.votes.count %>
        </div>
        <div style="clear: both;"></div>
      </div>
      <div class="main">
        <%= simple_format h quote.quote %>
      </div>
    </div>
  <% end %>
</div>

<!--<div id="sbar">
  <div class="box">
    <span class="title">QDB Statistics</span>
    <p>Total quotes: <%= @quotes.count %></p>
  </div>

  <div class="box">
    <%= render 'form' %>
  </div>
-->
  <%= paginate @quotes %>

</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quote:</b>
  <%= simple_format h @quote.quote %>
</p>


<%= link_to 'Back', quotes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip address:</b>
  <%= @vote.ip_address %>
</p>

<p>
  <b>Direction:</b>
  <%= @vote.direction %>
</p>

<p>
  <b>Quote:</b>
  <%= @vote.quote_id %>
</p>


<%= link_to 'Back', quotes_path(:page => params[:page]) %>